[package]
name = "libreplex_nifty_hybrid"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"
license = "MIT"
repository = "https://github.com/Libreplex/libreplex-program-library"

[lib]
crate-type = ["cdylib", "lib"]
name = "libreplex_nifty_hybrid"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build","anchor-lang/idl-build", "libreplex_fair_launch/idl-build"]

[dependencies]
anchor-lang = {version = "~0.30", features = ["init-if-needed"]}
anchor-spl = {version = "~0.30"}
libreplex_fair_launch = {path="../../../libreplex_fair_launch/programs/libreplex_fair_launch",version="*", features =["cpi", "no-entrypoint", "idl-build"]}
libreplex_shared = {version= "*", path="../../../libreplex_shared/programs/libreplex_shared", features=["no-entrypoint"] }
solana-program = "~1.18"
solana-address-lookup-table-program = "^1.17"
dyn-fmt = "0.3.0"
nifty-asset = {version = "0.5.0"}
libreplex-monoswap-client = {version = "*", path = "../../../monoswap/clients/rust/"}

[dev-dependencies]
solana-program-test = {version= "~1.18"}
